---

  - name : Création du dossier contenant le serveur
    file :
      path : /home/{{ user }}/{{ item }}
      state : directory
      owner : "{{ user }}"

  - name : Lien vers WWW
    become : yes
    file :
      src : /home/{{ user }}/{{ item }}
      dest : /var/www/{{ item }}
      owner :
      state : link
    notify : nginx reload

  - name : Créaiton de la configuration nginx
    become : yes
    template :
      src : templates/nginx.j2
      dest : /etc/nginx/sites-available/{{ item }}

  - name : Activation du domain {{ item }}
    become : yes
    file :
      src : /etc/nginx/sites-available/{{ item }}
      dest : /etc/nginx/sites-enabled/{{ item }}
      state : link
    notify : nginx reload

...
