---
   - name : Creation d'un utilisateur
     when : user is defined
     user : 
       name : "{{ user }}"
       comment : "Mon User"
       password : "userpass"
       shell : /bin/bash
       
   - name : Ajout d'une authorized key a partir d'un fichier
     when : user is defined
     authorized_key:
       user: "{{ user }}"
       key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
       
   - name : Ajout de {{ user }} dans sudoers
     when : user is defined
     template :
      src : templates/sudoers.j2
      dest : /etc/sudoers.d/{{ user }}-sudoer
      validate : visudo -cf %s 
...
